# Generated by Django 6.0.3 on 2026-03-31 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issueattachment",
            old_name="original_filename",
            new_name="filename",
        ),
    ]
