# Generated by Django 6.0.5 on 2026-05-16 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_rename_original_filename_issueattachment_filename"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="accessible_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
